In [1]:
import pandas as pd
import numpy as np
import scipy.stats as sp
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets.species_distributions import construct_grids
from sklearn.datasets import fetch_species_distributions
from sklearn.cluster import KMeans
from matplotlib import style
from mpl_toolkits.basemap import Basemap

In [2]:
dt = pd.read_csv("globalterrorismd.csv", encoding ='latin1')
dt.head()

C:\Users\Faculdade\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (4,6,31,33,53,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [3]:
ataques = []
for i in dt.attacktype1_txt:
    if i not in ataques:
        ataques.append(i)

paises = []
for i in dt.country_txt:
    if i not in paises:
        paises.append(i)

In [ ]:
def bayes_attack(x,y):
        dt_novo = dt[dt.attacktype1_txt == y]
        total = len(dt_novo)
        P = len(dt_novo[dt_novo.country_txt == x])/total
        return P

In [ ]:
dict_p ={}
for i in ataques:
    dict_p[i] = {}
    for k in paises:
        ind = 'P({0}|{1})'.format(k,i)
        P = bayes_attack(k,i)
        #print('P({0}|{1}) = {2}'.format(k,i,P)
        dict_p[i][k] = bayes_attack(k,i)
dict_p

In [ ]:
colo_colum = pd.DataFrame(dict_p)
colo_colum= colo_colum.head()
colo_colum['CODE'] = ['AFG','BEL','BIH','BLR','ARG']
colo_colum

In [ ]:
data = [dict(
    type = 'choropleth',
    #locations=colo_colum['CODE'],
    #z = colo_colum['Armed Assault'],
    #text = dt['country_txt'],
    autocolorscale = True,
    reversescale = True)]
data